/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-12 22:18:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ar.com.integrador.domain.Orador;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ar.com.integrador.domain.Orador");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>Proyecto Integrador Front | Grupo 1</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- aca va el header.jsp -->\r\n");
      out.write("		 ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <main>\r\n");
      out.write("        <section id=\"speakers\" class=\"container\">\r\n");
      out.write("            <h2 class=\"text-center\">\r\n");
      out.write("                <div>CONOCE A LOS</div>ORADORES\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div class=\"d-flex flex-wrap gap-2\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <img src=\"./assets/img/SteveJobs.jpg\" class=\"card-img-top\" alt=\"Steve Jobs\" loading=\"lazy\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <h4 class=\"backgroundYellow talkTopic\">JavaScript</h4>\r\n");
      out.write("                                <h4 class=\"ms-2 backgroundBlue talkTopic\">React</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3 class=\"card-title mb-4\">Steve Jobs</h3>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus earum voluptates rerum ipsaaccusamus, voluptas totam expedita quae quaerat consequuntur molestias libero tenetur nulla, architecto ex! Dolore similique error alias.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <img src=\"./assets/img/BillGates.jpg\" class=\"card-img-top\" alt=\"Bill Gates\" loading=\"lazy\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <h4 class=\"backgroundYellow talkTopic\">JavaScript</h4>\r\n");
      out.write("                                <h4 class=\"ms-2 backgroundBlue talkTopic\">React</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3 class=\"card-title mb-4\">Bill Gates</h3>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate ex debitis tempora blanditiis quos, expedita ut harum est praesentium modi dolorem voluptas, aspernatur tempore perferendis vero hic dolores magni. Reiciendis!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <img src=\"./assets/img/AdaLovalace.jpeg\" class=\"card-img-top\" alt=\"Ada Lovelace\" loading=\"lazy\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <h4 class=\"backgroundGray talkTopic\">Negocios</h4>\r\n");
      out.write("                                <h4 class=\"ms-2 backgroundRed talkTopic\">Startups</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3 class=\"card-title mb-4\">Ada Lovelace</h3>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos nisi natus aliquam dolore nihil\r\n");
      out.write("                                harum\r\n");
      out.write("                                debitis aut tempora tempore earum, est nam voluptates accusantium quo culpa maxime asperiores at\r\n");
      out.write("                                placeat.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("         </section>\r\n");
      out.write("		    <section class=\"container mb-4 text-center\" id=\"restoOradores\">\r\n");
      out.write("		       <a class=\"btn btn-outline-success\" href=\"");
      out.print(request.getContextPath());
      out.write("/FindAllOradorController\">Conoce al resto de los ORADORES</a>\r\n");
      out.write("		   </section>\r\n");
      out.write("        \r\n");
      out.write("        <section id=\"placeAndDate\" class=\"d-flex flex-column flex-lg-row w-100 gap-1\">\r\n");
      out.write("            <div class=\"col-12 col-lg-6 placeAndDate__img\"></div>\r\n");
      out.write("            <div class=\"col-12 col-lg-6 placeAndDate__info d-flex flex-column align-items-center align-items-lg-start text-center text-lg-start\">\r\n");
      out.write("                <h2 class=\"mb-4\">Bs As - Octubre</h2>\r\n");
      out.write("                <p class=\"mb-4\">Buenos Aires es la provincia y localidad más grande del estado de Argentina, en los Estados Unidos, Honolulu es la más sureña de entre las principales ciudades estadounidenses. Aunque el nombre de Honolulu se refiere al área urbana en la costa sureste de la isla de Oahu, la ciudad y el condado de Honolulu han formado una ciudad-condado consolidada que cubre toda la ciudad (aproximadamente 600 km<sup>2</sup> de superficie).</p>\r\n");
      out.write("                <a href=\"./pages/404.html\" class=\"buttons transparentBtn p-2\">Conocé más</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section id=\"speakerForm\" class=\"text-center col-lg-6 offset-lg-3\">\r\n");
      out.write("            <h2 class=\"speakerForm__h2\"><div>CONVIÉRTETE EN UN</div>ORADOR</h2>\r\n");
      out.write("            <p>Anótate como orador para dar una <span>charla ignate</span>. ¡Cuéntanos de qué quieres hablar!</p>\r\n");
      out.write("            \r\n");
      out.write("             <form action=\"");
      out.print(request.getContextPath());
      out.write("/CreateOradorController\" method=\"POST\">\r\n");
      out.write("		                   \r\n");
      out.write("            \r\n");
      out.write("            <form action=\"\" class=\"speakerForm__form text-start\">\r\n");
      out.write("                <div class=\"d-flex flex-column flex-lg-row gap-lg-5\">\r\n");
      out.write("                    <input type=\"text\" id=\"nombre\" name=\"nombre\" placeholder=\"Nombre\" class=\"my-3 w-100 p-3\">\r\n");
      out.write("                    <input type=\"text\" id=\"apellido\" name=\"apellido\" placeholder=\"Apellido\" class=\"my-3 w-100 p-3\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <textarea name=\"\" id=\"\" class=\"w-100 mt-3\">Sobre qué quieres hablar?</textarea>\r\n");
      out.write("                <p>Recuerda incluir un título para tu charla</p>\r\n");
      out.write("                <input type=\"submit\" value=\"Enviar\" class=\"w-100 buttons speakerForm__form__btn mt-3\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <!-- aca va el footer.jsp -->\r\n");
      out.write("		 ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
